SELECT @@DEFAULT_STORAGE_ENGINE;

CREATE TABLE FIELDS
(
	FIELD_ID	INT(10)	NOT NULL AUTO_INCREMENT,
	FIELD_NAME	VARCHAR(255) NOT NULL ,
	FIELD_ADDRESS	VARCHAR(255) NOT NULL ,
	CONSTRAINT FIELD_ID_PK	PRIMARY KEY (FIELD_ID)
);
ALTER TABLE FIELDS AUTO_INCREMENT=1;

CREATE TABLE HAY_STORAGE
(
	STORAGE_ID	INT(10)	NOT NULL AUTO_INCREMENT,
	STORAGE_NAME	VARCHAR(255) NOT NULL ,
	STORAGE_ADDRESS	VARCHAR(255) NOT NULL ,
	CONSTRAINT STORAGE_ID_PK	PRIMARY KEY (STORAGE_ID)
);
ALTER TABLE HAY_STORAGE AUTO_INCREMENT=1;

CREATE TABLE VET 
(
	VET_ID	INT(10)	NOT NULL AUTO_INCREMENT,
	VET_PHONE_NUM	VARCHAR(10)	NOT NULL ,
	VET_NAME	VARCHAR(25)	NOT NULL ,
	CONSTRAINT VET_ID_PK	PRIMARY KEY (VET_ID)
);
ALTER TABLE VET AUTO_INCREMENT=1;

CREATE TABLE LOGIN
(
	LOGIN_ID	INT(10)	NOT NULL AUTO_INCREMENT,
    USERNAME    VARCHAR(255) NOT NULL , 
	PASSWORD	VARCHAR(255)	NOT NULL ,
	LOGIN_RECOVERY_EMAIL	VARCHAR(255)	NOT NULL ,
	CONSTRAINT LOGIN_ID_PK	PRIMARY KEY (LOGIN_ID)
);
ALTER TABLE LOGIN AUTO_INCREMENT=1;

CREATE TABLE CATTLE
(
	CATTLE_ID	INT(10)	NOT NULL AUTO_INCREMENT,
	TAG_ID	VARCHAR(10) NOT NULL,
	VET_ID	INT(10)	NOT NULL,
	BUTCHER_DATE  DATE ,
	APT_DATE    DATE ,
	PASTURE_ID  INT(10) NOT NULL ,
	CATTLE_DEATH VARCHAR(255) , 
	CONSTRAINT CATTLE_ID_PK PRIMARY KEY (CATTLE_ID),
	CONSTRAINT VET_ID_FK FOREIGN KEY (VET_ID) REFERENCES VET (VET_ID) ON DELETE CASCADE ON UPDATE NO ACTION
);

ALTER TABLE CATTLE AUTO_INCREMENT=1;

CREATE TABLE HAY_BATCH
(
HAY_BATCH_ID INT(10) NOT NULL AUTO_INCREMENT,
HAY_BATCH_AMOUNT INT(10) NOT NULL ,
STORAGE_ID INT(10) NOT NULL ,
FIELD_ID	INT(10)	NOT NULL ,
PASTURE_ID	INT(10)	NOT NULL ,
HAY_BATCH_DATE DATE NOT NULL ,
TYPE_ID	VARCHAR(25) NOT NULL ,
CONSTRAINT HAY_BATCH_ID_PK PRIMARY KEY (HAY_BATCH_ID),
CONSTRAINT STORAGE_ID_FK FOREIGN KEY (STORAGE_ID) REFERENCES HAY_STORAGE (STORAGE_ID) ON DELETE CASCADE ON UPDATE NO ACTION,
CONSTRAINT FIELD_ID_HAY_BATCH_FK FOREIGN KEY (FIELD_ID) REFERENCES fields (FIELD_ID) ON DELETE CASCADE ON UPDATE NO ACTION

);
ALTER TABLE HAY_BATCH AUTO_INCREMENT=1;

CREATE TABLE PASTURE
(
	PASTURE_ID	INT(10) NOT NULL AUTO_INCREMENT ,
	PASTURE_NAME	VARCHAR(25) NOT NULL ,
	CATTLE_ID	INT(10)  ,
	HAY_BATCH_ID	INT(10)  ,
	CONSTRAINT PASTURE_ID_PK	PRIMARY KEY (PASTURE_ID),
	CONSTRAINT CATTLE_ID_PASTURE_FK FOREIGN KEY (CATTLE_ID) REFERENCES CATTLE (CATTLE_ID) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT HAY_BATCH_ID_PASTURE_FK FOREIGN KEY (HAY_BATCH_ID) REFERENCES HAY_BATCH (HAY_BATCH_ID) ON DELETE CASCADE ON UPDATE NO ACTION
);
ALTER TABLE PASTURE AUTO_INCREMENT=0;

ALTER TABLE HAY_BATCH ADD CONSTRAINT PASTURE_ID_HAY_BATCH_FK FOREIGN KEY (PASTURE_ID) REFERENCES PASTURE (PASTURE_ID) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE CATTLE ADD CONSTRAINT PASTURE_ID_FK FOREIGN KEY (PASTURE_ID) REFERENCES PASTURE (PASTURE_ID) ON DELETE CASCADE ON UPDATE NO ACTION;

CREATE TABLE CATTLE_TO_VET
(
	VET_ID	INT(10)	NOT NULL ,
	CATTLE_ID	INT(10)	NOT NULL ,
	CONSTRAINT CATTLE_TO_VAT_PK  PRIMARY KEY (VET_ID, CATTLE_ID),
	CONSTRAINT CATTLE_TO_VAT_FK1 FOREIGN KEY (CATTLE_ID) REFERENCES CATTLE (CATTLE_ID) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT CATTLE_TO_VAT_FK2 FOREIGN KEY (VET_ID) REFERENCES VET (VET_ID) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE FIELD_TO_CATTLE
(
FIELD_ID INT(10) NOT NULL ,
CATTLE_ID INT(10) NOT NULL ,
CONSTRAINT FIELD_TO_CATTLE_PK PRIMARY KEY (FIELD_ID, CATTLE_ID),
CONSTRAINT FIELD_TO_CATTLE_FK1 FOREIGN KEY (FIELD_ID) REFERENCES FIELDS (FIELD_ID) ON DELETE CASCADE ON UPDATE NO ACTION,
CONSTRAINT FIELD_TO_CATTLE_FK2 FOREIGN KEY (CATTLE_ID) REFERENCES CATTLE (CATTLE_ID) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE CATTLE_TO_HAY_BATCH
(
CATTLE_ID INT(10) NOT NULL ,
HAY_BATCH_ID INT(10) NOT NULL ,
CONSTRAINT CATTLE_TO_HAY_BATCH_PK PRIMARY KEY (CATTLE_ID, HAY_BATCH_ID),
CONSTRAINT CATTLE_TO_HAY_BATCH_FK1 FOREIGN KEY (CATTLE_ID) REFERENCES CATTLE (CATTLE_ID) ON DELETE CASCADE ON UPDATE NO ACTION,
CONSTRAINT CATTLE_TO_HAY_BATCH_FK2 FOREIGN KEY (HAY_BATCH_ID) REFERENCES HAY_BATCH (HAY_BATCH_ID) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE CATTLE_TO_PASTURE
(
	CATTLE_ID	INT(10)	NOT NULL ,
	PASTURE_ID	INT(10)	NOT NULL ,
	CONSTRAINT CATTLE_TO_PASTURE_PK  PRIMARY KEY (CATTLE_ID,PASTURE_ID),
	CONSTRAINT CATTLE_TO_PASTURE_FK1 FOREIGN KEY (CATTLE_ID) REFERENCES CATTLE (CATTLE_ID) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT CATTLE_TO_PASTURE_FK2 FOREIGN KEY (PASTURE_ID) REFERENCES PASTURE (PASTURE_ID) ON DELETE CASCADE ON UPDATE NO ACTION
);	

CREATE TABLE FIELD_TO_HAY_BATCH
(
	FIELD_ID	INT(10)	NOT NULL ,
	HAY_BATCH_ID	INT(10)	NOT NULL ,
	CONSTRAINT FIELD_TO_HAY_BATCH_PK  PRIMARY KEY (FIELD_ID,HAY_BATCH_ID),
	CONSTRAINT FIELD_TO_HAY_BATCH_FK1 FOREIGN KEY (FIELD_ID) REFERENCES FIELDS (FIELD_ID) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT FIELD_TO_HAY_BATCH_FK2 FOREIGN KEY (HAY_BATCH_ID) REFERENCES HAY_BATCH (HAY_BATCH_ID) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE HAY_BATCH_TO_PASTURE
(
	HAY_BATCH_ID	INT(10)	NOT NULL ,
	PASTURE_ID	INT(10)	NOT NULL ,
	CONSTRAINT HAY_BATCH_TO_PASTURE_PK  PRIMARY KEY (HAY_BATCH_ID,PASTURE_ID),
	CONSTRAINT HAY_BATCH_TO_PASTURE_FK1 FOREIGN KEY (HAY_BATCH_ID) REFERENCES HAY_BATCH (HAY_BATCH_ID) ON DELETE CASCADE ON UPDATE NO ACTION,
	CONSTRAINT HAY_BATCH_TO_PASTURE_FK2 FOREIGN KEY (PASTURE_ID) REFERENCES PASTURE (PASTURE_ID) ON DELETE CASCADE ON UPDATE NO ACTION
);




INSERT INTO fields (field_name, field_address) VALUES ('Daves', '244 Old Frame Rd');
INSERT INTO fields (field_name, field_address) VALUES ('Front', '244 Old Frame Rd');
INSERT INTO fields (field_name, field_address) VALUES ('Paps', '244 Old Frame Rd');
INSERT INTO fields ( field_name, field_address) VALUES ('Jump Well', '244 Old Frame Rd');
INSERT INTO fields (field_name, field_address) VALUES ('GasWell', '244 Old Frame Rd');

INSERT INTO fields (field_name, field_address) VALUES ('Bottom', '388 Gans Hill School Rd');
INSERT INTO fields (field_name, field_address) VALUES ('Barn', '388 Gans Hill School Rd');
INSERT INTO fields ( field_name, field_address) VALUES ('Back Barn', '388 Gans Hill School Rd');
INSERT INTO fields (field_name, field_address) VALUES ('Upper Barn', '388 Gans Hill School Rd');
INSERT INTO fields (field_name, field_address) VALUES ('Lost Bottom', '388 Gans Hill School Rd');
INSERT INTO fields ( field_name, field_address) VALUES ('Lower Creek', '388 Gans Hill School Rd');
INSERT INTO fields (field_name, field_address) VALUES ('Middle', '388 Gans Hill School Rd');
INSERT INTO fields (field_name, field_address) VALUES ('Cemetary', '388 Gans Hill School Rd');
INSERT INTO fields ( field_name, field_address) VALUES ('Top', '388 Gans Hill School Rd');
INSERT INTO fields ( field_name, field_address) VALUES ('Blaney Hollow', '388 Gans Hill School Rd');

INSERT INTO hay_storage (storage_name, STORAGE_ADDRESS) VALUES ('Scholtis II Storage', '388 Gans Hill School Rd');
INSERT INTO hay_storage (storage_name, STORAGE_ADDRESS) VALUES ('Scholtis I Storage', '244 Old Frame Rd');



INSERT INTO Pasture (pasture_name) VALUES ('Pasture Cemetary');
INSERT INTO Pasture (pasture_name) VALUES ('Pasture Cow');
INSERT INTO Pasture (pasture_name) VALUES ('Pasture Barn');
INSERT INTO Pasture (pasture_name) VALUES ('Pasture Thorn');


INSERT INTO VET (VET_PHONE_NUM, VET_NAME) VALUES (1231231234, 'VET1');
INSERT INTO VET (VET_PHONE_NUM, VET_NAME) VALUES (1231231234, 'VET2');
INSERT INTO VET (VET_PHONE_NUM, VET_NAME) VALUES (1231231234, 'VET3');
INSERT INTO VET (VET_PHONE_NUM, VET_NAME) VALUES (1231231234, 'VET4');

